const fs = require('fs');
const g = fs.readFileSync('assets/js/games.js', 'utf8');
const s = fs.readFileSync('assets/js/stories.js', 'utf8');
const gl = fs.readFileSync('glossary.html', 'utf8');
const e = fs.readFileSync('assets/js/easter-eggs.js', 'utf8');
const tl = fs.readFileSync('assets/js/timeline.js', 'utf8');
const q = fs.readFileSync('assets/js/quiz.js', 'utf8');
const ws = fs.readFileSync('assets/js/workshop.js', 'utf8');
const dict = fs.readFileSync('assets/js/core/i18n-dict.js', 'utf8');
console.log('游戏: ' + (g.match(/id: '/g) || []).length + ' 款');
console.log('每日: ' + (g.match(/DAILY_IDS = \[([^\]]+)\]/)[1].trim().split(',').length) + ' 款');
const pm = s.match(/window\.PEOPLE = \[([\s\S]*?)\n  \];/);
if (pm) console.log('人物: ' + (pm[1].match(/'[a-z0-9-]+'/g) || []).length + ' 位');
const am = s.match(/window\.ARTIFACTS = \[([\s\S]*?)\n  \];/);
if (am) console.log('密件: ' + (am[1].match(/id: '[a-z0-9-]+'/g) || []).length + ' 件');
console.log('术语: ' + ((gl.match(/term: '/g) || []).length + (gl.match(/term: "/g) || []).length) + ' 词');
console.log('彩蛋: ' + (e.match(/id: 'e\d+'/g) || []).length + ' 条');
const tm = tl.match(/window\.CRYPTO_TIMELINE = \[([\s\S]*?)\n\];/);
if (tm) console.log('时间线: ' + (tm[1].match(/y: -?\d+/g) || []).length + ' 节点');
console.log('测验题: ' + (q.match(/lvl: /g) || []).length + ' 题');
console.log('工坊算法: ' + (ws.match(/name: '[^']+'/g) || []).length + ' 种');
console.log('根页面: ' + fs.readdirSync('.').filter(f => /\.html$/.test(f)).length + ' 个');
console.log('游戏目录: ' + fs.readdirSync('games').length + ' 个');
console.log('stp 人物键: ' + (dict.match(/stp\.[a-z0-9-]+\.name/g) || []).length + ' 条');
console.log('sta 密件键: ' + (dict.match(/sta\.[a-z0-9-]+\.name/g) || []).length + ' 条');
